"""
Weekly Bet Card — the automated slate.
Shows top conviction plays, then ranked tables grouped by prop type.
Reads data/processed/bet_card_latest.parquet (generated by pipeline.generate_bet_card).
"""
import streamlit as st
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
PROC_DIR = PROJECT_ROOT / "data" / "processed"

st.set_page_config(page_title="Bet Card | NFL Analytics", page_icon="🎯", layout="wide")

# Friendly market names + display order
MARKET_NAMES = {
    "player_pass_yds": "Passing Yards",
    "player_pass_tds": "Passing TDs",
    "player_rush_yds": "Rushing Yards",
    "player_receptions": "Receptions",
    "player_reception_yds": "Receiving Yards",
    "player_anytime_td": "Anytime TD",
}
MARKET_ORDER = [
    "player_pass_yds", "player_pass_tds", "player_rush_yds",
    "player_receptions", "player_reception_yds", "player_anytime_td",
]
TIER_RANK = {"HIGH": 0, "MEDIUM": 1, "LOW": 2, "SPECULATIVE": 3, "LOW-LINE": 4}


st.title("🎯 Weekly Bet Card")

card_path = PROC_DIR / "bet_card_latest.parquet"
if not card_path.exists():
    st.warning("No bet card generated yet. Run: `python -m pipeline.generate_bet_card`")
    st.info("The card populates once player props are live on FanDuel (usually Tue-Wed of game week).")
    st.stop()

card = pd.read_parquet(card_path)

# Normalize columns
card["tier_rank"] = card["confidence_tier"].map(TIER_RANK).fillna(9)
card["dir_label"] = card["direction"].str.upper()
card["market_name"] = card["market"].map(MARKET_NAMES).fillna(card["market"])

# Header metrics
games_note = f"{card['home_team'].nunique()} games" if "home_team" in card.columns else ""
c1, c2, c3 = st.columns(3)
with c1:
    st.metric("Total Plays", len(card))
with c2:
    st.metric("High Conviction", int((card["confidence_tier"] == "HIGH").sum()))
with c3:
    over = (card["direction"] == "over").sum()
    under = (card["direction"] == "under").sum()
    st.metric("Over / Under", f"{over} / {under}")

st.caption(f"Generated from live FanDuel lines. {games_note}. Re-run the generator to refresh.")
st.markdown("---")


# ===== TOP CONVICTION PLAYS (across all markets) =====
st.markdown("### 🔥 Highest Conviction Plays")
st.caption("Top plays across every prop type, ranked by model/strategy confidence.")

# Exclude low-line flagged plays from the top conviction list
_top_pool = card[card["confidence_tier"] != "LOW-LINE"] if "confidence_tier" in card.columns else card
top = _top_pool.sort_values(["tier_rank", "confidence"], ascending=[True, False]).head(12)

top_display = top[["dir_label", "player", "market_name", "line", "units", "confidence_tier"]].copy()
top_display.columns = ["Bet", "Player", "Prop", "Line", "Units", "Tier"]
st.dataframe(
    top_display,
    use_container_width=True,
    hide_index=True,
    column_config={
        "Units": st.column_config.NumberColumn(format="%.1f u"),
        "Line": st.column_config.NumberColumn(format="%.1f"),
    },
)

st.markdown("---")

# ===== BY PROP TYPE =====
st.markdown("### 📊 All Plays by Prop Type")
st.caption("Every flagged play grouped by market, ranked highest to lowest conviction, with the reason.")

# Build tabs only for markets that have plays
markets_present = [m for m in MARKET_ORDER if m in card["market"].unique()]
if markets_present:
    tabs = st.tabs([MARKET_NAMES[m] for m in markets_present])
    for tab, market in zip(tabs, markets_present):
        with tab:
            sub = card[card["market"] == market].sort_values(
                ["tier_rank", "confidence"], ascending=[True, False]
            )
            over_ct = (sub["direction"] == "over").sum()
            under_ct = (sub["direction"] == "under").sum()
            st.caption(f"{len(sub)} plays — {over_ct} OVER, {under_ct} UNDER")

            for _, r in sub.iterrows():
                emoji = "🟢" if r["direction"] == "over" else "🔴"
                st.markdown(
                    f"{emoji} **{r['dir_label']} {r['player']}** {r['line']:.1f} "
                    f"· {r['units']:.1f}u · _{r['confidence_tier']}_"
                )
                note = r.get("reasoning", "")
                if note:
                    st.caption(note)
else:
    st.info("No market breakdowns available yet.")

st.markdown("---")
st.caption("Bet responsibly. Lines move — verify current numbers on FanDuel before placing.")
